### ISSUE TITLE
Tasmanian LIST Server Change

### ISSUE THREAD

**Issue by Tinkicka** [mholling/nswtopo#35]
It looks like LIST have done some housekeeping and changed the server.

When I run the script for TAS maps it hangs at PLACENAMES and returns an error that no such service exists. Upon looking at the REST endpoint, a MapServer titled PLACENAMES no longer exists. It now appears to be located under SEARCHSERVICE with a layer titled NAMEDFEATURES.

lt may take some code changes that are beyond my level of ability to fix.

Brett

**Comment by klaashartmann** [comment]
A rough hack is to remove the place names source and all features that require that layer. You end up with some missing data (e.g. white space instead of lakes), however it's still a usable map.

**Comment by apiddington** [comment]
I've just heard from DPIPWE that PlacenamePoints service has been reinstated and it all seems to work OK with the current version (1.6.1).
The SearchService returns a polygon rather than a point. I did play around with using it making changes to topgraphic.yml, but it either put the label on the the first segment (and so in totally the wrong place for a peak), or labelled every segment (again not what you want for a peak). It would require some code changes and determining the centre of the polygon to make it useful.

**Comment by mholling** [comment]
Version 2 has big/incompatible changes to I took the TAS layers offline until I get a chance to update them

**Comment by Thoroslives** [comment]
Any update on Tasmania layers from List?

**Comment by apiddington** [comment]
I hadn't used it for a couple of years, but last week I noticed that the PlacenamePoints service was missing again. Have sent 3 emails to the List, but no response so far.

I investigated using the SearchService again and have got it working.

Commented out all existing placenames stuff and then added:
**_In sources:_**
  placenames:
    #host: services.thelist.tas.gov.au
    url: https://services.thelist.tas.gov.au
    folder: Public
    service: SearchService
**_In features:_**
  feature-names:
  - source: placenames
    name: Named Features
    where:
    - TYPE IN ('BAY', 'BEACH', 'BUILDING', 'CAMPING GROUND', 'ESTUARY', 'HILL', 'ISLAND', 'ISTHMUS', 'MOUNTAIN', 'MOUNTAIN PEAK', 'MOUNTAINS', 'PASS', 'PLAIN', 'PLATEAU', 'PROMONTORY', 'RESERVOIR', 'RIDGE', 'VALLEY', 'WATER BODY', 'WATERFALL')
    - NOM_REG_NO IS NOT NULL
    - NAME NOT LIKE '%UNOFFICIAL%' AND NAME NOT LIKE '%SUPERSEDED%' AND NOT NAME = 'TASMANIA'
    label-only: true
    label: NAME
**_and in labels:_**
  feature-names:
    font-family: Calibri, Arial, Helvetica, sans-serif
    font-style: normal
    font-size: 2.0
    letter-spacing: 0.1
    position: [ over, right, above, below, left ]
    margin: 0.7
    reduce: centroids

I also made a couple of changes to label.rb to set the names from the SearchService to proper case, rather than capitals.

Having peaks as a polygon is not ideal. If your map includes part of the polygon, but not the actual peak, the name appears in the centre of the part of the polygon on the map.

You'll also need to comment out the geoscience-australia stuff because that doesn't seem to be published any more.

Hope this helps you.
