### ISSUE TITLE
Vegetation Layer

### ISSUE THREAD

**Issue by nswwalker** [mholling/nswtopo#5]
I'm having some problems getting the vegetation layer working in the script. The nsw gov no longer seem to be serving up the v1 vegetation data and the best I seem to be able to do is v2 data. 

For what ever reason that seems to cause the script to bomb out when creating the raster files - presumably because vegetation data isn't in the format it was expecting.

Has anyone got it working with the v2 data? Or does anyone have the v1 data they'd be happy to share?

**Comment by cnschulz** [comment]
Similar issue here. couldn't find source for 'vegetation'

**Comment by tombrennan06** [comment]
Not sure about your issue. I've previously had to hack the script a bit to get the vegetation working. That was over a year ago so there have probably been some changes since then.Can't be sure you have the same issue. There is a thread on bushwalk.com - http://bushwalk.com/forum/viewtopic.php?f=36&t=9028 which has quite a few people who have played with the script and got it working on it. I think it's probably the place you're most likely to get help.
